// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: tensorflow/python/framework/op_reg_offset.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpRegOffset describes the location of an op registration (i.e. where
// REGISTER_OP is called).
type OpRegOffset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the op.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Filepath of where the op is registered.
	Filepath string `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	// The start offset of the op registration in the file.
	Start uint32 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	// The end offset of the op registration in the file.
	End uint32 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *OpRegOffset) Reset() {
	*x = OpRegOffset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_python_framework_op_reg_offset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRegOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRegOffset) ProtoMessage() {}

func (x *OpRegOffset) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_python_framework_op_reg_offset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRegOffset.ProtoReflect.Descriptor instead.
func (*OpRegOffset) Descriptor() ([]byte, []int) {
	return file_tensorflow_python_framework_op_reg_offset_proto_rawDescGZIP(), []int{0}
}

func (x *OpRegOffset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpRegOffset) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *OpRegOffset) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *OpRegOffset) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

// OpRegOffsets is a collection of OpRegOffset.
type OpRegOffsets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offsets []*OpRegOffset `protobuf:"bytes,1,rep,name=offsets,proto3" json:"offsets,omitempty"`
}

func (x *OpRegOffsets) Reset() {
	*x = OpRegOffsets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_python_framework_op_reg_offset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRegOffsets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRegOffsets) ProtoMessage() {}

func (x *OpRegOffsets) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_python_framework_op_reg_offset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRegOffsets.ProtoReflect.Descriptor instead.
func (*OpRegOffsets) Descriptor() ([]byte, []int) {
	return file_tensorflow_python_framework_op_reg_offset_proto_rawDescGZIP(), []int{1}
}

func (x *OpRegOffsets) GetOffsets() []*OpRegOffset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

var File_tensorflow_python_framework_op_reg_offset_proto protoreflect.FileDescriptor

var file_tensorflow_python_framework_op_reg_offset_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x79, 0x74,
	0x68, 0x6f, 0x6e, 0x2f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6f, 0x70,
	0x5f, 0x72, 0x65, 0x67, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x22, 0x65, 0x0a,
	0x0b, 0x4f, 0x70, 0x52, 0x65, 0x67, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x22, 0x41, 0x0a, 0x0c, 0x4f, 0x70, 0x52, 0x65, 0x67, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c,
	0x6f, 0x77, 0x2e, 0x4f, 0x70, 0x52, 0x65, 0x67, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x07,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73, 0x42, 0xb1, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e,
	0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x42, 0x10, 0x4f, 0x70, 0x52, 0x65,
	0x67, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x45,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x72, 0x65, 0x6e,
	0x61, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x2f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0xa2, 0x02, 0x03, 0x54, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x54, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0xca, 0x02, 0x0a, 0x54, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x66, 0x6c, 0x6f, 0x77, 0xe2, 0x02, 0x16, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c,
	0x6f, 0x77, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0a, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_tensorflow_python_framework_op_reg_offset_proto_rawDescOnce sync.Once
	file_tensorflow_python_framework_op_reg_offset_proto_rawDescData = file_tensorflow_python_framework_op_reg_offset_proto_rawDesc
)

func file_tensorflow_python_framework_op_reg_offset_proto_rawDescGZIP() []byte {
	file_tensorflow_python_framework_op_reg_offset_proto_rawDescOnce.Do(func() {
		file_tensorflow_python_framework_op_reg_offset_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_python_framework_op_reg_offset_proto_rawDescData)
	})
	return file_tensorflow_python_framework_op_reg_offset_proto_rawDescData
}

var file_tensorflow_python_framework_op_reg_offset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tensorflow_python_framework_op_reg_offset_proto_goTypes = []interface{}{
	(*OpRegOffset)(nil),  // 0: tensorflow.OpRegOffset
	(*OpRegOffsets)(nil), // 1: tensorflow.OpRegOffsets
}
var file_tensorflow_python_framework_op_reg_offset_proto_depIdxs = []int32{
	0, // 0: tensorflow.OpRegOffsets.offsets:type_name -> tensorflow.OpRegOffset
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tensorflow_python_framework_op_reg_offset_proto_init() }
func file_tensorflow_python_framework_op_reg_offset_proto_init() {
	if File_tensorflow_python_framework_op_reg_offset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_python_framework_op_reg_offset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpRegOffset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_python_framework_op_reg_offset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpRegOffsets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_python_framework_op_reg_offset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_python_framework_op_reg_offset_proto_goTypes,
		DependencyIndexes: file_tensorflow_python_framework_op_reg_offset_proto_depIdxs,
		MessageInfos:      file_tensorflow_python_framework_op_reg_offset_proto_msgTypes,
	}.Build()
	File_tensorflow_python_framework_op_reg_offset_proto = out.File
	file_tensorflow_python_framework_op_reg_offset_proto_rawDesc = nil
	file_tensorflow_python_framework_op_reg_offset_proto_goTypes = nil
	file_tensorflow_python_framework_op_reg_offset_proto_depIdxs = nil
}
