// Copyright 2022 The TensorFlow Authors. All Rights Reserved.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//==============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: tensorflow/compiler/xla/mlir/tools/mlir_replay/public/compiler_trace.proto

package public

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MlirCompilationTraceEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the pass that was previously executed.
	AfterPass *string `protobuf:"bytes,1,opt,name=after_pass,json=afterPass" json:"after_pass,omitempty"`
	// MLIR module IR of the state after the pass.
	MlirModule *string `protobuf:"bytes,2,opt,name=mlir_module,json=mlirModule" json:"mlir_module,omitempty"`
}

func (x *MlirCompilationTraceEntry) Reset() {
	*x = MlirCompilationTraceEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MlirCompilationTraceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlirCompilationTraceEntry) ProtoMessage() {}

func (x *MlirCompilationTraceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlirCompilationTraceEntry.ProtoReflect.Descriptor instead.
func (*MlirCompilationTraceEntry) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescGZIP(), []int{0}
}

func (x *MlirCompilationTraceEntry) GetAfterPass() string {
	if x != nil && x.AfterPass != nil {
		return *x.AfterPass
	}
	return ""
}

func (x *MlirCompilationTraceEntry) GetMlirModule() string {
	if x != nil && x.MlirModule != nil {
		return *x.MlirModule
	}
	return ""
}

type MlirCompilationTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// MLIR modules corresponding to each stage of the compilation pipeline.
	Passes []*MlirCompilationTraceEntry `protobuf:"bytes,1,rep,name=passes" json:"passes,omitempty"`
}

func (x *MlirCompilationTrace) Reset() {
	*x = MlirCompilationTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MlirCompilationTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlirCompilationTrace) ProtoMessage() {}

func (x *MlirCompilationTrace) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlirCompilationTrace.ProtoReflect.Descriptor instead.
func (*MlirCompilationTrace) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescGZIP(), []int{1}
}

func (x *MlirCompilationTrace) GetPasses() []*MlirCompilationTraceEntry {
	if x != nil {
		return x.Passes
	}
	return nil
}

var File_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto protoreflect.FileDescriptor

var file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDesc = []byte{
	0x0a, 0x4a, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x6d, 0x6c, 0x69, 0x72, 0x2f, 0x74,
	0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x6d, 0x6c, 0x69, 0x72, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x79,
	0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72,
	0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6d, 0x6c,
	0x69, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x22, 0x5b,
	0x0a, 0x19, 0x4d, 0x6c, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x66, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x66, 0x74, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6c,
	0x69, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x6c, 0x69, 0x72, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x5b, 0x0a, 0x14, 0x4d,
	0x6c, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x72,
	0x61, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x6c, 0x69, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x6c, 0x69, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x65, 0x73, 0x42, 0xec, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d,
	0x2e, 0x6d, 0x6c, 0x69, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65,
	0x72, 0x42, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x5f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x72, 0x65, 0x6e, 0x61, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x74,
	0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67,
	0x65, 0x6e, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x6d, 0x6c, 0x69, 0x72, 0x2f,
	0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x6d, 0x6c, 0x69, 0x72, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x61,
	0x79, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0xa2, 0x02, 0x03, 0x4d, 0x49, 0x58, 0xaa, 0x02,
	0x10, 0x4d, 0x6c, 0x69, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65,
	0x72, 0xca, 0x02, 0x10, 0x4d, 0x6c, 0x69, 0x72, 0x5c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x65, 0x74, 0x65, 0x72, 0xe2, 0x02, 0x1c, 0x4d, 0x6c, 0x69, 0x72, 0x5c, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4d, 0x6c, 0x69, 0x72, 0x3a, 0x3a, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x72,
}

var (
	file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescOnce sync.Once
	file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescData = file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDesc
)

func file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescGZIP() []byte {
	file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescOnce.Do(func() {
		file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescData)
	})
	return file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDescData
}

var file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_goTypes = []interface{}{
	(*MlirCompilationTraceEntry)(nil), // 0: mlir.interpreter.MlirCompilationTraceEntry
	(*MlirCompilationTrace)(nil),      // 1: mlir.interpreter.MlirCompilationTrace
}
var file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_depIdxs = []int32{
	0, // 0: mlir.interpreter.MlirCompilationTrace.passes:type_name -> mlir.interpreter.MlirCompilationTraceEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_init() }
func file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_init() {
	if File_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MlirCompilationTraceEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MlirCompilationTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_goTypes,
		DependencyIndexes: file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_depIdxs,
		MessageInfos:      file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_msgTypes,
	}.Build()
	File_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto = out.File
	file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_rawDesc = nil
	file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_goTypes = nil
	file_tensorflow_compiler_xla_mlir_tools_mlir_replay_public_compiler_trace_proto_depIdxs = nil
}
