// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: tensorflow/core/tfrt/graph_executor/test_config.proto

package graph_executor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestConfig1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *TestConfig1) Reset() {
	*x = TestConfig1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_core_tfrt_graph_executor_test_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestConfig1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConfig1) ProtoMessage() {}

func (x *TestConfig1) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_core_tfrt_graph_executor_test_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConfig1.ProtoReflect.Descriptor instead.
func (*TestConfig1) Descriptor() ([]byte, []int) {
	return file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescGZIP(), []int{0}
}

func (x *TestConfig1) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type TestConfig2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *TestConfig2) Reset() {
	*x = TestConfig2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_core_tfrt_graph_executor_test_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestConfig2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConfig2) ProtoMessage() {}

func (x *TestConfig2) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_core_tfrt_graph_executor_test_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConfig2.ProtoReflect.Descriptor instead.
func (*TestConfig2) Descriptor() ([]byte, []int) {
	return file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescGZIP(), []int{1}
}

func (x *TestConfig2) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_tensorflow_core_tfrt_graph_executor_test_config_proto protoreflect.FileDescriptor

var file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDesc = []byte{
	0x0a, 0x35, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x74, 0x66, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66,
	0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x66, 0x72, 0x74, 0x5f, 0x73, 0x74, 0x75, 0x62, 0x22, 0x1f, 0x0a,
	0x0b, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x31, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x1f,
	0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x32, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x42,
	0xe7, 0x01, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c,
	0x6f, 0x77, 0x2e, 0x74, 0x66, 0x72, 0x74, 0x5f, 0x73, 0x74, 0x75, 0x62, 0x42, 0x0f, 0x54, 0x65,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x72, 0x65,
	0x6e, 0x61, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e,
	0x67, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x66, 0x72, 0x74, 0x2f,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0xa2, 0x02,
	0x03, 0x54, 0x54, 0x58, 0xaa, 0x02, 0x13, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x54, 0x66, 0x72, 0x74, 0x53, 0x74, 0x75, 0x62, 0xca, 0x02, 0x13, 0x54, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x5c, 0x54, 0x66, 0x72, 0x74, 0x53, 0x74, 0x75, 0x62,
	0xe2, 0x02, 0x1f, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x5c, 0x54, 0x66,
	0x72, 0x74, 0x53, 0x74, 0x75, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x14, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x3a,
	0x3a, 0x54, 0x66, 0x72, 0x74, 0x53, 0x74, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescOnce sync.Once
	file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescData = file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDesc
)

func file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescGZIP() []byte {
	file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescOnce.Do(func() {
		file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescData)
	})
	return file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDescData
}

var file_tensorflow_core_tfrt_graph_executor_test_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tensorflow_core_tfrt_graph_executor_test_config_proto_goTypes = []interface{}{
	(*TestConfig1)(nil), // 0: tensorflow.tfrt_stub.TestConfig1
	(*TestConfig2)(nil), // 1: tensorflow.tfrt_stub.TestConfig2
}
var file_tensorflow_core_tfrt_graph_executor_test_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tensorflow_core_tfrt_graph_executor_test_config_proto_init() }
func file_tensorflow_core_tfrt_graph_executor_test_config_proto_init() {
	if File_tensorflow_core_tfrt_graph_executor_test_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_core_tfrt_graph_executor_test_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestConfig1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_core_tfrt_graph_executor_test_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestConfig2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_core_tfrt_graph_executor_test_config_proto_goTypes,
		DependencyIndexes: file_tensorflow_core_tfrt_graph_executor_test_config_proto_depIdxs,
		MessageInfos:      file_tensorflow_core_tfrt_graph_executor_test_config_proto_msgTypes,
	}.Build()
	File_tensorflow_core_tfrt_graph_executor_test_config_proto = out.File
	file_tensorflow_core_tfrt_graph_executor_test_config_proto_rawDesc = nil
	file_tensorflow_core_tfrt_graph_executor_test_config_proto_goTypes = nil
	file_tensorflow_core_tfrt_graph_executor_test_config_proto_depIdxs = nil
}
