// Copyright 2023 The TensorFlow Authors. All Rights Reserved.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//==============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: tensorflow/compiler/xla/python/pjrt_ifrt/xla_host_callback.proto

package pjrt_ifrt

import (
	data "github.com/airenas/go-tf-serving-protogen/tensorflow/compiler/xla/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a host callback in an XLA computation.
//
// XLA computation may use XLA send/recv to represent communication between the
// host and the device. This can be used to implement "host callbacks", where
// host-side computation is invoked in the middle of XLA computation. This
// message contains information that is necessary to instantiate host callbacks
// that are marshalled from the client.
//
// Modeled after `xla::HostCallback`.
type XlaHostCallbackProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The metadata (e.g. channel_id, shape) for the operands and results.
	Operands []*XlaHostCallbackProto_ArgInfo `protobuf:"bytes,1,rep,name=operands,proto3" json:"operands,omitempty"`
	Results  []*XlaHostCallbackProto_ArgInfo `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// Serialized host callback.
	SerializedCallback *anypb.Any `protobuf:"bytes,3,opt,name=serialized_callback,json=serializedCallback,proto3" json:"serialized_callback,omitempty"`
	// See comment for PJRT
	// ExecuteOptions::use_major_to_minor_data_layout_for_callbacks.
	UseMajorToMinorDataLayoutForCallbacks bool `protobuf:"varint,4,opt,name=use_major_to_minor_data_layout_for_callbacks,json=useMajorToMinorDataLayoutForCallbacks,proto3" json:"use_major_to_minor_data_layout_for_callbacks,omitempty"`
}

func (x *XlaHostCallbackProto) Reset() {
	*x = XlaHostCallbackProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XlaHostCallbackProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XlaHostCallbackProto) ProtoMessage() {}

func (x *XlaHostCallbackProto) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XlaHostCallbackProto.ProtoReflect.Descriptor instead.
func (*XlaHostCallbackProto) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescGZIP(), []int{0}
}

func (x *XlaHostCallbackProto) GetOperands() []*XlaHostCallbackProto_ArgInfo {
	if x != nil {
		return x.Operands
	}
	return nil
}

func (x *XlaHostCallbackProto) GetResults() []*XlaHostCallbackProto_ArgInfo {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *XlaHostCallbackProto) GetSerializedCallback() *anypb.Any {
	if x != nil {
		return x.SerializedCallback
	}
	return nil
}

func (x *XlaHostCallbackProto) GetUseMajorToMinorDataLayoutForCallbacks() bool {
	if x != nil {
		return x.UseMajorToMinorDataLayoutForCallbacks
	}
	return false
}

type XlaHostCallbackProto_ArgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id associated with this value in HLO. Declared as `uint32`
	// even though `xla::HostCallbackArgInfo::channel_id` is `uint16_t` because
	// protobuf doesn't have a 16-bit integer type.
	ChannelId uint32 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The host shape for the value.
	Shape *data.ShapeProto `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
}

func (x *XlaHostCallbackProto_ArgInfo) Reset() {
	*x = XlaHostCallbackProto_ArgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XlaHostCallbackProto_ArgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XlaHostCallbackProto_ArgInfo) ProtoMessage() {}

func (x *XlaHostCallbackProto_ArgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XlaHostCallbackProto_ArgInfo.ProtoReflect.Descriptor instead.
func (*XlaHostCallbackProto_ArgInfo) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescGZIP(), []int{0, 0}
}

func (x *XlaHostCallbackProto_ArgInfo) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *XlaHostCallbackProto_ArgInfo) GetShape() *data.ShapeProto {
	if x != nil {
		return x.Shape
	}
	return nil
}

var File_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto protoreflect.FileDescriptor

var file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDesc = []byte{
	0x0a, 0x40, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e,
	0x2f, 0x70, 0x6a, 0x72, 0x74, 0x5f, 0x69, 0x66, 0x72, 0x74, 0x2f, 0x78, 0x6c, 0x61, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x78, 0x6c, 0x61, 0x2e, 0x69, 0x66, 0x72, 0x74, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x26, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66,
	0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61,
	0x2f, 0x78, 0x6c, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x91, 0x03, 0x0a, 0x14, 0x58, 0x6c, 0x61, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x42, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x78, 0x6c, 0x61,
	0x2e, 0x69, 0x66, 0x72, 0x74, 0x2e, 0x58, 0x6c, 0x61, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x67, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x40, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x78, 0x6c, 0x61, 0x2e, 0x69, 0x66, 0x72, 0x74, 0x2e, 0x58, 0x6c, 0x61, 0x48, 0x6f, 0x73, 0x74,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x45,
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x12, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x5b, 0x0a, 0x2c, 0x75, 0x73, 0x65, 0x5f, 0x6d, 0x61, 0x6a,
	0x6f, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x25, 0x75, 0x73, 0x65,
	0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x54, 0x6f, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x73, 0x1a, 0x4f, 0x0a, 0x07, 0x41, 0x72, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x05,
	0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x78, 0x6c,
	0x61, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x73, 0x68,
	0x61, 0x70, 0x65, 0x42, 0xb9, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x6c, 0x61, 0x2e,
	0x69, 0x66, 0x72, 0x74, 0x42, 0x14, 0x58, 0x6c, 0x61, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x52, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x72, 0x65, 0x6e, 0x61, 0x73,
	0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c,
	0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f,
	0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x2f, 0x70, 0x6a, 0x72, 0x74, 0x5f, 0x69, 0x66, 0x72, 0x74,
	0xa2, 0x02, 0x03, 0x58, 0x49, 0x58, 0xaa, 0x02, 0x08, 0x58, 0x6c, 0x61, 0x2e, 0x49, 0x66, 0x72,
	0x74, 0xca, 0x02, 0x08, 0x58, 0x6c, 0x61, 0x5c, 0x49, 0x66, 0x72, 0x74, 0xe2, 0x02, 0x14, 0x58,
	0x6c, 0x61, 0x5c, 0x49, 0x66, 0x72, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x58, 0x6c, 0x61, 0x3a, 0x3a, 0x49, 0x66, 0x72, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescOnce sync.Once
	file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescData = file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDesc
)

func file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescGZIP() []byte {
	file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescOnce.Do(func() {
		file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescData)
	})
	return file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDescData
}

var file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_goTypes = []interface{}{
	(*XlaHostCallbackProto)(nil),         // 0: xla.ifrt.XlaHostCallbackProto
	(*XlaHostCallbackProto_ArgInfo)(nil), // 1: xla.ifrt.XlaHostCallbackProto.ArgInfo
	(*anypb.Any)(nil),                    // 2: google.protobuf.Any
	(*data.ShapeProto)(nil),              // 3: xla.ShapeProto
}
var file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_depIdxs = []int32{
	1, // 0: xla.ifrt.XlaHostCallbackProto.operands:type_name -> xla.ifrt.XlaHostCallbackProto.ArgInfo
	1, // 1: xla.ifrt.XlaHostCallbackProto.results:type_name -> xla.ifrt.XlaHostCallbackProto.ArgInfo
	2, // 2: xla.ifrt.XlaHostCallbackProto.serialized_callback:type_name -> google.protobuf.Any
	3, // 3: xla.ifrt.XlaHostCallbackProto.ArgInfo.shape:type_name -> xla.ShapeProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_init() }
func file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_init() {
	if File_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XlaHostCallbackProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XlaHostCallbackProto_ArgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_goTypes,
		DependencyIndexes: file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_depIdxs,
		MessageInfos:      file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_msgTypes,
	}.Build()
	File_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto = out.File
	file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_rawDesc = nil
	file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_goTypes = nil
	file_tensorflow_compiler_xla_python_pjrt_ifrt_xla_host_callback_proto_depIdxs = nil
}
